from fpdf import FPDF
import os
from PIL import Image as PILImage # Renamed to avoid conflict with FPDF Image logic

class PDFReport(FPDF):
    def header(self):
        # --- Top Blue Banner ---
        self.set_fill_color(30, 144, 255)
        self.rect(0, 0, 210, 18, 'F') # Reduced height slightly
        
        self.set_font('Arial', 'B', 13)
        self.set_text_color(255, 255, 255) 
        self.set_xy(10, 5)
        self.cell(0, 10, 'MediScan AI - Diagnostic Report', 0, 0, 'L')
        
        self.set_font('Arial', '', 9)
        self.set_xy(160, 5)
        self.cell(40, 10, 'CONFIDENTIAL', 0, 0, 'R')
        self.ln(20)

    def footer(self):
        self.set_y(-12)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Single-Page Summary | Generated by MediScan AI', 0, 0, 'C')

def clean_markdown(text):
    text = text.replace('**', '').replace('__', '')
    return text.encode('latin-1', 'replace').decode('latin-1')

def create_medical_pdf(patient_data, analysis_data, deep_eval, image_path, output_filename="report.pdf"):
    pdf = PDFReport()
    # Disable auto page break to force single page logic
    pdf.set_auto_page_break(auto=False, margin=10)
    pdf.add_page()
    
    # --- 1. PATIENT INFO GRID ---
    pdf.set_fill_color(245, 248, 255)
    pdf.set_draw_color(220, 220, 220)
    
    start_y = pdf.get_y()
    pdf.rect(10, start_y, 190, 20, 'DF') # Compact box
    
    pdf.set_font('Arial', 'B', 9)
    pdf.set_text_color(50, 50, 50)
    
    # Row 1
    pdf.set_xy(15, start_y + 4)
    pdf.cell(25, 6, "PATIENT:", 0, 0)
    pdf.set_font('Arial', '', 9)
    pdf.cell(65, 6, patient_data['name'], 0, 0)
    
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(20, 6, "ID:", 0, 0)
    pdf.set_font('Arial', '', 9)
    pdf.cell(50, 6, str(patient_data['id']), 0, 1)
    
    # Row 2
    pdf.set_xy(15, start_y + 10)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(25, 6, "AGE/SEX:", 0, 0)
    pdf.set_font('Arial', '', 9)
    pdf.cell(65, 6, f"{patient_data['age']} / {patient_data['sex']}", 0, 0)
    
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(20, 6, "DATE:", 0, 0)
    pdf.set_font('Arial', '', 9)
    pdf.cell(50, 6, str(patient_data['date']), 0, 1)
    
    pdf.ln(14) # Compact spacing

    # --- 2. FINDINGS & ASSESSMENT (Combined to save space) ---
    
    # Header
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(30, 144, 255)
    pdf.cell(0, 6, "CLINICAL ANALYSIS", 0, 1, 'L')
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    # Primary Organ & Findings
    pdf.set_font('Arial', 'B', 9)
    pdf.set_text_color(0, 0, 0)
    organ = analysis_data.get('organ', 'Unknown').upper()
    pdf.write(5, f"TARGET ORGAN: {organ}")
    pdf.ln(6)

    # Findings List
    findings = analysis_data.get('findings', [])
    if findings:
        for item in findings:
            cond = item.get('condition', 'Unknown')
            sev = item.get('severity', 'N/A')
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(50, 50, 50)
            pdf.write(5, f"{chr(149)} {cond} ")
            
            # Colored Severity
            pdf.set_font('Arial', 'B', 8)
            if "High" in sev: pdf.set_text_color(200, 0, 0)
            elif "Med" in sev: pdf.set_text_color(200, 140, 0)
            else: pdf.set_text_color(0, 128, 0)
            pdf.write(5, f"[{sev}]")
            pdf.ln(5)
            pdf.set_text_color(0,0,0) # Reset
    else:
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(0, 5, "No specific anomalies detected.", 0, 1)
        
    pdf.ln(3)

    # Deep Evaluation Text
    pdf.set_font('Arial', '', 9)
    lines = deep_eval.split('\n')
    for line in lines:
        line = clean_markdown(line).strip()
        if not line: continue
        if "Risk_Score" in line or "Risk_Percentage" in line:
             pdf.ln(1)
             pdf.set_font('Arial', 'B', 9)
             pdf.set_fill_color(255, 240, 240)
             pdf.cell(0, 6, line, 0, 1, 'L', fill=True)
        elif line.startswith('-'):
            pdf.set_font('Arial', '', 9)
            pdf.multi_cell(0, 4, chr(149) + " " + line[1:].strip())
        else:
            pdf.multi_cell(0, 4, line)
    
    # --- 3. DYNAMIC IMAGE RESIZING ---
    
    pdf.ln(5)
    current_y = pdf.get_y()
    
    # A4 Height = 297mm. 
    # Footer starts at -15mm (approx 282mm).
    # We leave a 5mm buffer.
    max_y_position = 275 
    available_height = max_y_position - current_y
    
    if available_height > 30 and os.path.exists(image_path):
        pdf.set_font('Arial', 'B', 11)
        pdf.set_text_color(30, 144, 255)
        pdf.cell(0, 6, "VISUAL EVIDENCE", 0, 1, 'L')
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        
        # Recalculate available height after the header
        available_height = max_y_position - pdf.get_y() - 5 # -5 for caption
        
        # Get Image Dimensions using PIL to calculate aspect ratio
        try:
            with PILImage.open(image_path) as img:
                img_w, img_h = img.size
                aspect_ratio = img_w / img_h
                
                # Constraints
                max_width = 150 # Max width on page (centering it)
                
                # Calculate width if we fit by height
                width_by_height = available_height * aspect_ratio
                
                if width_by_height <= max_width:
                    # Height is the limiting factor (or perfectly fits)
                    final_h = available_height
                    final_w = width_by_height
                else:
                    # Width is the limiting factor
                    final_w = max_width
                    final_h = max_width / aspect_ratio

                # Center the image
                x_pos = (210 - final_w) / 2
                pdf.image(image_path, x=x_pos, y=pdf.get_y()+2, w=final_w, h=final_h)
                
                # Caption (Placed below image)
                pdf.set_y(pdf.get_y() + final_h + 3)
                pdf.set_font('Arial', 'I', 8)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 4, "Figure 1: Annotated Area of Interest", 0, 1, 'C')
                
        except Exception as e:
            pdf.set_font('Arial', '', 8)
            pdf.cell(0, 10, f"Could not load image: {str(e)}", 0, 1)
    else:
        # Not enough space
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "[Visuals omitted to fit single page]", 0, 1, 'C')

    return pdf.output(dest='S').encode('latin-1')